### ISSUE TITLE
Feedback: Uso das Labels

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/Drive-Safe-Walk-Safe#15]
Acredito que foi passado na monitoria de github mas só reforçando o cadastramento e uso das Labels, em caso de dúvidas é só falar. Lembrando que a nomenclatura e as suas respectivas cores devem ser respeitadas (como mostrado na imagem).

![6cf291b6-24dc-11e7-9cb2-a325c1979945](https://cloud.githubusercontent.com/assets/11631238/26494938/ac6a8a96-41f7-11e7-9d58-3384a2c0a65d.png)

https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by auronperalta** [comment]
Corrigido!

**Comment by auronperalta** [comment]
Tem problema eu deixar uma label minha chamada "Feito", pra eu mesmo ter o controle das que ja foram implementadas?

**Comment by jorgehclinhares** [comment]
Sem problemas, vocês podem criar labels extras para gerenciamento interno
de vocês. Mas é bom tentarem usar ao máximo essas que eu citei :D

Em 26/05/2017 22:03, "auronperalta" <notifications@github.com> escreveu:
